on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run graph tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # TODO: Test a real graph
      - name: Run graph-validator tests
        uses: logseq/graph-validator@main
